version: '2'
services:
#  web:
#    image: web:latest
#    links:
#      - "mysql:db"
#    ports:
#      - "9000:9000"
#    volumes:
#      - ./:/app
#    command: ["/run.sh"]
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./schema.sql:/schema.sql